// Code generated by "weapstat"; DO NOT EDIT.

package pastselfinmirror

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   48,
		HPAdd:    7.2,
		ATKBase:  24,
		ATKAdd:   3.6,
		DEFBase:  24,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 30,
		HPBase:   105.6,
		HPAdd:    7.2,
		ATKBase:  52.8,
		ATKAdd:   3.6,
		DEFBase:  52.8,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 40,
		HPBase:   182.4,
		HPAdd:    7.2,
		ATKBase:  91.2,
		ATKAdd:   3.6,
		DEFBase:  91.2,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 50,
		HPBase:   259.2,
		HPAdd:    7.2,
		ATKBase:  129.6,
		ATKAdd:   3.6,
		DEFBase:  129.6,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 60,
		HPBase:   336,
		HPAdd:    7.2,
		ATKBase:  168,
		ATKAdd:   3.6,
		DEFBase:  168,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 70,
		HPBase:   412.8,
		HPAdd:    7.2,
		ATKBase:  206.4,
		ATKAdd:   3.6,
		DEFBase:  206.4,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 80,
		HPBase:   489.6,
		HPAdd:    7.2,
		ATKBase:  244.8,
		ATKAdd:   3.6,
		DEFBase:  244.8,
		DEFAdd:   3.6,
	},
}