// Code generated by "charstat"; DO NOT EDIT.

package luocha

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    102.96,
		ATKAdd:     5.148,
		DEFBase:    49.5,
		DEFAdd:     2.475,
		HPBase:     174.24,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    144.144,
		ATKAdd:     5.148,
		DEFBase:    69.3,
		DEFAdd:     2.475,
		HPBase:     243.936,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    185.328,
		ATKAdd:     5.148,
		DEFBase:    89.1,
		DEFAdd:     2.475,
		HPBase:     313.632,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    226.512,
		ATKAdd:     5.148,
		DEFBase:    108.9,
		DEFAdd:     2.475,
		HPBase:     383.328,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    267.696,
		ATKAdd:     5.148,
		DEFBase:    128.7,
		DEFAdd:     2.475,
		HPBase:     453.024,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    308.88,
		ATKAdd:     5.148,
		DEFBase:    148.5,
		DEFAdd:     2.475,
		HPBase:     522.72,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    350.064,
		ATKAdd:     5.148,
		DEFBase:    168.3,
		DEFAdd:     2.475,
		HPBase:     592.416,
		HPAdd:      8.712,
		SPD:        101,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 6,
	},
	"209": {
		Stat: prop.HPPercent,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}