// Code generated by "charstat"; DO NOT EDIT.

package herta

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    79.20000000018626,
		ATKAdd:     3.9600000008940697,
		DEFBase:    54,
		DEFAdd:     2.700000000651926,
		HPBase:     129.6000000005588,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    110.88000000081956,
		ATKAdd:     3.9600000008940697,
		DEFBase:    75.6000000005588,
		DEFAdd:     2.700000000651926,
		HPBase:     181.44000000040978,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    142.56000000052154,
		ATKAdd:     3.9600000008940697,
		DEFBase:    97.20000000018626,
		DEFAdd:     2.700000000651926,
		HPBase:     233.28000000026077,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    174.24000000022352,
		ATKAdd:     3.9600000008940697,
		DEFBase:    118.80000000074506,
		DEFAdd:     2.700000000651926,
		HPBase:     285.12000000011176,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    205.92000000085682,
		ATKAdd:     3.9600000008940697,
		DEFBase:    140.40000000037253,
		DEFAdd:     2.700000000651926,
		HPBase:     336.96000000089407,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    237.6000000005588,
		ATKAdd:     3.9600000008940697,
		DEFBase:    162,
		DEFAdd:     2.700000000651926,
		HPBase:     388.80000000074506,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    269.28000000026077,
		ATKAdd:     3.9600000008940697,
		DEFBase:    183.6000000005588,
		DEFAdd:     2.700000000651926,
		HPBase:     440.64000000059605,
		HPAdd:      6.480000000447035,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 2,
	},
	"203": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Ascension: 3,
	},
	"205": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 5,
	},
	"207": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.10000000009313226,
		Level: 75,
	},
	"210": {
		Stat: prop.IceDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}