// Code generated by "charstat"; DO NOT EDIT.

package bronya

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    79.20000000018626,
		ATKAdd:     3.9600000008940697,
		DEFBase:    72.6000000005588,
		DEFAdd:     3.630000000586733,
		HPBase:     168.96000000089407,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    110.88000000081956,
		ATKAdd:     3.9600000008940697,
		DEFBase:    101.64000000059605,
		DEFAdd:     3.630000000586733,
		HPBase:     236.54400000022724,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    142.56000000052154,
		ATKAdd:     3.9600000008940697,
		DEFBase:    130.6800000006333,
		DEFAdd:     3.630000000586733,
		HPBase:     304.1279999995604,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    174.24000000022352,
		ATKAdd:     3.9600000008940697,
		DEFBase:    159.72000000067055,
		DEFAdd:     3.630000000586733,
		HPBase:     371.7120000005234,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    205.92000000085682,
		ATKAdd:     3.9600000008940697,
		DEFBase:    188.7600000007078,
		DEFAdd:     3.630000000586733,
		HPBase:     439.2959999998566,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    237.6000000005588,
		ATKAdd:     3.9600000008940697,
		DEFBase:    217.80000000074506,
		DEFAdd:     3.630000000586733,
		HPBase:     506.88000000081956,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    269.28000000026077,
		ATKAdd:     3.9600000008940697,
		DEFBase:    246.8400000007823,
		DEFAdd:     3.630000000586733,
		HPBase:     574.4640000001527,
		HPAdd:      8.447999999858439,
		SPD:        99,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.WindDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.CritDMG,
		Amount: 0.05299999983981252,
		Ascension: 2,
	},
	"203": {
		Stat: prop.WindDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.WindDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritDMG,
		Amount: 0.0800000000745058,
		Ascension: 5,
	},
	"207": {
		Stat: prop.WindDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritDMG,
		Amount: 0.10699999961070716,
		Level: 75,
	},
	"210": {
		Stat: prop.WindDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}