// Code generated by "weapstat"; DO NOT EDIT.

package baptismofpurethought

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   43.2,
		HPAdd:    6.48,
		ATKBase:  26.4,
		ATKAdd:   3.96,
		DEFBase:  24,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 30,
		HPBase:   95.04,
		HPAdd:    6.48,
		ATKBase:  58.08,
		ATKAdd:   3.96,
		DEFBase:  52.8,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 40,
		HPBase:   164.16,
		HPAdd:    6.48,
		ATKBase:  100.32,
		ATKAdd:   3.96,
		DEFBase:  91.2,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 50,
		HPBase:   233.28,
		HPAdd:    6.48,
		ATKBase:  142.56,
		ATKAdd:   3.96,
		DEFBase:  129.6,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 60,
		HPBase:   302.4,
		HPAdd:    6.48,
		ATKBase:  184.8,
		ATKAdd:   3.96,
		DEFBase:  168,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 70,
		HPBase:   371.52,
		HPAdd:    6.48,
		ATKBase:  227.04,
		ATKAdd:   3.96,
		DEFBase:  206.4,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 80,
		HPBase:   440.64,
		HPAdd:    6.48,
		ATKBase:  269.28,
		ATKAdd:   3.96,
		DEFBase:  244.8,
		DEFAdd:   3.6,
	},
}