// Code generated by "charstat"; DO NOT EDIT.

package yanqing

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    92.40000000037253,
		ATKAdd:     4.62000000057742,
		DEFBase:    56.10000000009313,
		DEFAdd:     2.8050000004004687,
		HPBase:     121.44000000040978,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    129.36000000033528,
		ATKAdd:     4.62000000057742,
		DEFBase:    78.54000000050291,
		DEFAdd:     2.8050000004004687,
		HPBase:     170.0159999995958,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    166.32000000029802,
		ATKAdd:     4.62000000057742,
		DEFBase:    100.9800000009127,
		DEFAdd:     2.8050000004004687,
		HPBase:     218.59200000041164,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    203.28000000026077,
		ATKAdd:     4.62000000057742,
		DEFBase:    123.42000000039116,
		DEFAdd:     2.8050000004004687,
		HPBase:     267.16799999959767,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    240.24000000022352,
		ATKAdd:     4.62000000057742,
		DEFBase:    145.86000000080094,
		DEFAdd:     2.8050000004004687,
		HPBase:     315.7440000004135,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    277.20000000018626,
		ATKAdd:     4.62000000057742,
		DEFBase:    168.3000000002794,
		DEFAdd:     2.8050000004004687,
		HPBase:     364.320000000298,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    314.160000000149,
		ATKAdd:     4.62000000057742,
		DEFBase:    190.74000000068918,
		DEFAdd:     2.8050000004004687,
		HPBase:     412.89600000041537,
		HPAdd:      6.071999999927357,
		SPD:        109,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.IceDamagePercent,
		Amount: 0.06399999978020787,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}