// Code generated by "charstat"; DO NOT EDIT.

package welt

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    84.48000000044703,
		ATKAdd:     4.2239999999292195,
		DEFBase:    69.3000000002794,
		DEFAdd:     3.465000000083819,
		HPBase:     153.12000000011176,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    118.27200000011362,
		ATKAdd:     4.2239999999292195,
		DEFBase:    97.02000000001863,
		DEFAdd:     3.465000000083819,
		HPBase:     214.36799999978393,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    152.0639999997802,
		ATKAdd:     4.2239999999292195,
		DEFBase:    124.74000000068918,
		DEFAdd:     3.465000000083819,
		HPBase:     275.6160000001546,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    185.85600000037812,
		ATKAdd:     4.2239999999292195,
		DEFBase:    152.4600000004284,
		DEFAdd:     3.465000000083819,
		HPBase:     336.86400000052527,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    219.6480000000447,
		ATKAdd:     4.2239999999292195,
		DEFBase:    180.18000000016764,
		DEFAdd:     3.465000000083819,
		HPBase:     398.1119999999646,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    253.44000000040978,
		ATKAdd:     4.2239999999292195,
		DEFBase:    207.9000000008382,
		DEFAdd:     3.465000000083819,
		HPBase:     459.3600000003353,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    287.23200000007637,
		ATKAdd:     4.2239999999292195,
		DEFBase:    235.62000000057742,
		DEFAdd:     3.465000000083819,
		HPBase:     520.6080000000075,
		HPAdd:      7.6560000001918525,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.06399999978020787,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}