// Code generated by "weapstat"; DO NOT EDIT.

package alongthepassingshore

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   48,
		HPAdd:    7.2,
		ATKBase:  28.8,
		ATKAdd:   4.32,
		DEFBase:  18,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 30,
		HPBase:   105.6,
		HPAdd:    7.2,
		ATKBase:  63.36,
		ATKAdd:   4.32,
		DEFBase:  39.6,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 40,
		HPBase:   182.4,
		HPAdd:    7.2,
		ATKBase:  109.44,
		ATKAdd:   4.32,
		DEFBase:  68.4,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 50,
		HPBase:   259.2,
		HPAdd:    7.2,
		ATKBase:  155.52,
		ATKAdd:   4.32,
		DEFBase:  97.2,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 60,
		HPBase:   336,
		HPAdd:    7.2,
		ATKBase:  201.6,
		ATKAdd:   4.32,
		DEFBase:  126,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 70,
		HPBase:   412.8,
		HPAdd:    7.2,
		ATKBase:  247.68,
		ATKAdd:   4.32,
		DEFBase:  154.8,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 80,
		HPBase:   489.6,
		HPAdd:    7.2,
		ATKBase:  293.76,
		ATKAdd:   4.32,
		DEFBase:  183.6,
		DEFAdd:   2.7,
	},
}