---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  protos: .task/protos

tasks:
  default: task -l
  lint:
    desc: run golangci-lint and tests
    cmds:
      - go test ./pkg/... ./tests/...
      - golangci-lint run --fast --fix --print-issued-lines=false --out-format=colored-line-number --issues-exit-code=0
