---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  protos: .task/protos

tasks:
  default: task -l
  lint:
    desc: run golangci-lint and tests
    cmds:
      - go test ./pkg/... ./tests/...
      - golangci-lint run --fast --fix --print-issued-lines=false --out-format=colored-line-number --issues-exit-code=0
  servermode:
    desc: watches for change and launches server mode
    watch: true
    sources:
      - "**/*.go"
    vars:
      WIN_CMD: Get-CimInstance -ClassName Win32_PRocess -Filter "CommandLine LIKE '%GCSIM_SERVER%'" | ForEach-Object -Process {taskkill /F /PID $_.ProcessId}
    cmds:
      - cmd: powershell {{shellQuote .WIN_CMD}}
        platforms: [windows]
        ignore_error: true
      - cmd: pkill -f SRSIM_SERVER=1
        platforms: [linux, darwin]
        ignore_error: true
      - go run cmd/server/main.go SRSIM_SERVER=1
  webdev:
    internal: true
    dir: js
    cmd: pnpm start
