// Code generated by "weapstat"; DO NOT EDIT.

package thedaythecosmosfell

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   43.2,
		HPAdd:    6.48,
		ATKBase:  21.6,
		ATKAdd:   3.24,
		DEFBase:  15,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 30,
		HPBase:   95.04,
		HPAdd:    6.48,
		ATKBase:  47.52,
		ATKAdd:   3.24,
		DEFBase:  33,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 40,
		HPBase:   164.16,
		HPAdd:    6.48,
		ATKBase:  82.08,
		ATKAdd:   3.24,
		DEFBase:  57,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 50,
		HPBase:   233.28,
		HPAdd:    6.48,
		ATKBase:  116.64,
		ATKAdd:   3.24,
		DEFBase:  81,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 60,
		HPBase:   302.4,
		HPAdd:    6.48,
		ATKBase:  151.2,
		ATKAdd:   3.24,
		DEFBase:  105,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 70,
		HPBase:   371.52,
		HPAdd:    6.48,
		ATKBase:  185.76,
		ATKAdd:   3.24,
		DEFBase:  129,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 80,
		HPBase:   440.64,
		HPAdd:    6.48,
		ATKBase:  220.32,
		ATKAdd:   3.24,
		DEFBase:  153,
		DEFAdd:   2.25,
	},
}