// Code generated by "charstat"; DO NOT EDIT.

package himeko

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    102.96000000089407,
		ATKAdd:     5.147999999579042,
		DEFBase:    59.40000000037253,
		DEFAdd:     2.970000000903383,
		HPBase:     142.56000000052154,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    144.1439999998547,
		ATKAdd:     5.147999999579042,
		DEFBase:    83.16000000014901,
		DEFAdd:     2.970000000903383,
		HPBase:     199.5840000002645,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    185.32799999974668,
		ATKAdd:     5.147999999579042,
		DEFBase:    106.92000000085682,
		DEFAdd:     2.970000000903383,
		HPBase:     256.60800000000745,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    226.51200000033714,
		ATKAdd:     5.147999999579042,
		DEFBase:    130.6800000006333,
		DEFAdd:     2.970000000903383,
		HPBase:     313.6320000004489,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    267.6960000002291,
		ATKAdd:     5.147999999579042,
		DEFBase:    154.44000000040978,
		DEFAdd:     2.970000000903383,
		HPBase:     370.65600000019185,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    308.88000000081956,
		ATKAdd:     5.147999999579042,
		DEFBase:    178.20000000018626,
		DEFAdd:     2.970000000903383,
		HPBase:     427.6800000006333,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    350.0639999997802,
		ATKAdd:     5.147999999579042,
		DEFBase:    201.96000000089407,
		DEFAdd:     2.970000000903383,
		HPBase:     484.70400000037625,
		HPAdd:      7.127999999560416,
		SPD:        96,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.FireDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.FireDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.FireDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.FireDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.FireDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}