// Code generated by "charstat"; DO NOT EDIT.

package pela

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    74.40000000037253,
		ATKAdd:     3.7200000006705523,
		DEFBase:    63,
		DEFAdd:     3.1500000001396984,
		HPBase:     134.40000000037253,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    104.16000000014901,
		ATKAdd:     3.7200000006705523,
		DEFBase:    88.20000000018626,
		DEFAdd:     3.1500000001396984,
		HPBase:     188.160000000149,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    133.92000000085682,
		ATKAdd:     3.7200000006705523,
		DEFBase:    113.40000000037253,
		DEFAdd:     3.1500000001396984,
		HPBase:     241.92000000085682,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    163.6800000006333,
		ATKAdd:     3.7200000006705523,
		DEFBase:    138.6000000005588,
		DEFAdd:     3.1500000001396984,
		HPBase:     295.6800000006333,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    193.44000000040978,
		ATKAdd:     3.7200000006705523,
		DEFBase:    163.80000000074506,
		DEFAdd:     3.1500000001396984,
		HPBase:     349.4400000004098,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    223.20000000018626,
		ATKAdd:     3.7200000006705523,
		DEFBase:    189,
		DEFAdd:     3.1500000001396984,
		HPBase:     403.20000000018626,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    252.96000000089407,
		ATKAdd:     3.7200000006705523,
		DEFBase:    214.20000000018626,
		DEFAdd:     3.1500000001396984,
		HPBase:     456.96000000089407,
		HPAdd:      6.720000000670552,
		SPD:        105,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectHitRate,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectHitRate,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.IceDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}