// Code generated by "charstat"; DO NOT EDIT.

package asta

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    69.6000000005588,
		ATKAdd:     3.480000000447035,
		DEFBase:    63,
		DEFAdd:     3.1500000001396984,
		HPBase:     139.20000000018626,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    97.44000000040978,
		ATKAdd:     3.480000000447035,
		DEFBase:    88.20000000018626,
		DEFAdd:     3.1500000001396984,
		HPBase:     194.88000000081956,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    125.28000000026077,
		ATKAdd:     3.480000000447035,
		DEFBase:    113.40000000037253,
		DEFAdd:     3.1500000001396984,
		HPBase:     250.56000000052154,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    153.12000000011176,
		ATKAdd:     3.480000000447035,
		DEFBase:    138.6000000005588,
		DEFAdd:     3.1500000001396984,
		HPBase:     306.2400000002235,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    180.96000000089407,
		ATKAdd:     3.480000000447035,
		DEFBase:    163.80000000074506,
		DEFAdd:     3.1500000001396984,
		HPBase:     361.9200000008568,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    208.80000000074506,
		ATKAdd:     3.480000000447035,
		DEFBase:    189,
		DEFAdd:     3.1500000001396984,
		HPBase:     417.6000000005588,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    236.64000000059605,
		ATKAdd:     3.480000000447035,
		DEFBase:    214.20000000018626,
		DEFAdd:     3.1500000001396984,
		HPBase:     473.28000000026077,
		HPAdd:      6.96000000089407,
		SPD:        106,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.FireDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 2,
	},
	"203": {
		Stat: prop.FireDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Ascension: 3,
	},
	"205": {
		Stat: prop.FireDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 5,
	},
	"207": {
		Stat: prop.FireDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.10000000009313226,
		Level: 75,
	},
	"210": {
		Stat: prop.FireDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}