// Code generated by "weapstat"; DO NOT EDIT.

package planetaryrendezvous

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   48,
		HPAdd:    7.2000000001862645,
		ATKBase:  19.200000000186265,
		ATKAdd:   2.880000000819564,
		DEFBase:  15,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 30,
		HPBase:   105.6000000005588,
		HPAdd:    7.2000000001862645,
		ATKBase:  42.24000000022352,
		ATKAdd:   2.880000000819564,
		DEFBase:  33,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 40,
		HPBase:   182.40000000037253,
		HPAdd:    7.2000000001862645,
		ATKBase:  72.96000000089407,
		ATKAdd:   2.880000000819564,
		DEFBase:  57,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 50,
		HPBase:   259.20000000018626,
		HPAdd:    7.2000000001862645,
		ATKBase:  103.6800000006333,
		ATKAdd:   2.880000000819564,
		DEFBase:  81,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 60,
		HPBase:   336,
		HPAdd:    7.2000000001862645,
		ATKBase:  134.40000000037253,
		ATKAdd:   2.880000000819564,
		DEFBase:  105,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 70,
		HPBase:   412.80000000074506,
		HPAdd:    7.2000000001862645,
		ATKBase:  165.12000000011176,
		ATKAdd:   2.880000000819564,
		DEFBase:  129,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 80,
		HPBase:   489.6000000005588,
		HPAdd:    7.2000000001862645,
		ATKBase:  195.8400000007823,
		ATKAdd:   2.880000000819564,
		DEFBase:  153,
		DEFAdd:   2.2500000002328306,
	},
}