// Code generated by "charstat"; DO NOT EDIT.

package natasha

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    64.80000000074506,
		ATKAdd:     3.2400000002235174,
		DEFBase:    69,
		DEFAdd:     3.450000000419095,
		HPBase:     158.40000000037253,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    90.72000000067055,
		ATKAdd:     3.2400000002235174,
		DEFBase:    96.6000000005588,
		DEFAdd:     3.450000000419095,
		HPBase:     221.7600000007078,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    116.64000000059605,
		ATKAdd:     3.2400000002235174,
		DEFBase:    124.20000000018626,
		DEFAdd:     3.450000000419095,
		HPBase:     285.12000000011176,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    142.56000000052154,
		ATKAdd:     3.2400000002235174,
		DEFBase:    151.80000000074506,
		DEFAdd:     3.450000000419095,
		HPBase:     348.48000000044703,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    168.48000000044703,
		ATKAdd:     3.2400000002235174,
		DEFBase:    179.40000000037253,
		DEFAdd:     3.450000000419095,
		HPBase:     411.8400000007823,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    194.40000000037253,
		ATKAdd:     3.2400000002235174,
		DEFBase:    207,
		DEFAdd:     3.450000000419095,
		HPBase:     475.20000000018626,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    220.32000000029802,
		ATKAdd:     3.2400000002235174,
		DEFBase:    234.6000000005588,
		DEFAdd:     3.450000000419095,
		HPBase:     538.5600000005215,
		HPAdd:      7.920000000856817,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"1105101": {
		Ascension: 2,
	},
	"1105102": {
		Ascension: 4,
	},
	"1105103": {
		Ascension: 6,
	},
	"1105201": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"1105202": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"1105203": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"1105204": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 3,
	},
	"1105205": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"1105206": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"1105207": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"1105208": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 6,
	},
	"1105209": {
		Stat: prop.EffectRES,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"1105210": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}