// Code generated by "charstat"; DO NOT EDIT.

package qingque

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    88.80000000074506,
		ATKAdd:     4.440000000409782,
		DEFBase:    60,
		DEFAdd:     3,
		HPBase:     139.20000000018626,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    124.32000000029802,
		ATKAdd:     4.440000000409782,
		DEFBase:    84,
		DEFAdd:     3,
		HPBase:     194.88000000081956,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    159.8400000007823,
		ATKAdd:     4.440000000409782,
		DEFBase:    108,
		DEFAdd:     3,
		HPBase:     250.56000000052154,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    195.36000000033528,
		ATKAdd:     4.440000000409782,
		DEFBase:    132,
		DEFAdd:     3,
		HPBase:     306.2400000002235,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    230.88000000081956,
		ATKAdd:     4.440000000409782,
		DEFBase:    156,
		DEFAdd:     3,
		HPBase:     361.9200000008568,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    266.40000000037253,
		ATKAdd:     4.440000000409782,
		DEFBase:    180,
		DEFAdd:     3,
		HPBase:     417.6000000005588,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    301.9200000008568,
		ATKAdd:     4.440000000409782,
		DEFBase:    204,
		DEFAdd:     3,
		HPBase:     473.28000000026077,
		HPAdd:      6.96000000089407,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 6,
	},
	"209": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.06399999978020787,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}