// Code generated by "charstat"; DO NOT EDIT.

package sushang

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    76.80000000074506,
		ATKAdd:     3.840000000782311,
		DEFBase:    57,
		DEFAdd:     2.850000000791624,
		HPBase:     124.80000000074506,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    107.52000000048429,
		ATKAdd:     3.840000000782311,
		DEFBase:    79.80000000074506,
		DEFAdd:     2.850000000791624,
		HPBase:     174.72000000067055,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    138.24000000022352,
		ATKAdd:     3.840000000782311,
		DEFBase:    102.6000000005588,
		DEFAdd:     2.850000000791624,
		HPBase:     224.64000000059605,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    168.96000000089407,
		ATKAdd:     3.840000000782311,
		DEFBase:    125.40000000037253,
		DEFAdd:     2.850000000791624,
		HPBase:     274.56000000052154,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    199.6800000006333,
		ATKAdd:     3.840000000782311,
		DEFBase:    148.20000000018626,
		DEFAdd:     2.850000000791624,
		HPBase:     324.48000000044703,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    230.40000000037253,
		ATKAdd:     3.840000000782311,
		DEFBase:    171,
		DEFAdd:     2.850000000791624,
		HPBase:     374.40000000037253,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    261.12000000011176,
		ATKAdd:     3.840000000782311,
		DEFBase:    193.80000000074506,
		DEFAdd:     2.850000000791624,
		HPBase:     424.320000000298,
		HPAdd:      6.240000000223517,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 6,
	},
	"209": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}