// Code generated by "weapstat"; DO NOT EDIT.

package todayisanotherpeacefulday

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   38.40000000037253,
		HPAdd:    5.760000000707805,
		ATKBase:  24,
		ATKAdd:   3.6000000005587935,
		DEFBase:  15,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 30,
		HPBase:   84.48000000044703,
		HPAdd:    5.760000000707805,
		ATKBase:  52.80000000074506,
		ATKAdd:   3.6000000005587935,
		DEFBase:  33,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 40,
		HPBase:   145.92000000085682,
		HPAdd:    5.760000000707805,
		ATKBase:  91.20000000018626,
		ATKAdd:   3.6000000005587935,
		DEFBase:  57,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 50,
		HPBase:   207.36000000033528,
		HPAdd:    5.760000000707805,
		ATKBase:  129.6000000005588,
		ATKAdd:   3.6000000005587935,
		DEFBase:  81,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 60,
		HPBase:   268.80000000074506,
		HPAdd:    5.760000000707805,
		ATKBase:  168,
		ATKAdd:   3.6000000005587935,
		DEFBase:  105,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 70,
		HPBase:   330.2400000002235,
		HPAdd:    5.760000000707805,
		ATKBase:  206.40000000037253,
		ATKAdd:   3.6000000005587935,
		DEFBase:  129,
		DEFAdd:   2.2500000002328306,
	},
	{
		MaxLevel: 80,
		HPBase:   391.6800000006333,
		HPAdd:    5.760000000707805,
		ATKBase:  244.80000000074506,
		ATKAdd:   3.6000000005587935,
		DEFBase:  153,
		DEFAdd:   2.2500000002328306,
	},
}