// Code generated by "charstat"; DO NOT EDIT.

package clara

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    100.32000000029802,
		ATKAdd:     5.015999999595806,
		DEFBase:    66,
		DEFAdd:     3.3000000002793968,
		HPBase:     168.96000000089407,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    140.44799999985844,
		ATKAdd:     5.015999999595806,
		DEFBase:    92.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     236.54400000022724,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    180.57600000011735,
		ATKAdd:     5.015999999595806,
		DEFBase:    118.80000000074506,
		DEFAdd:     3.3000000002793968,
		HPBase:     304.1279999995604,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    220.70400000037625,
		ATKAdd:     5.015999999595806,
		DEFBase:    145.20000000018626,
		DEFAdd:     3.3000000002793968,
		HPBase:     371.7120000005234,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    260.83200000063516,
		ATKAdd:     5.015999999595806,
		DEFBase:    171.6000000005588,
		DEFAdd:     3.3000000002793968,
		HPBase:     439.2959999998566,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    300.96000000089407,
		ATKAdd:     5.015999999595806,
		DEFBase:    198,
		DEFAdd:     3.3000000002793968,
		HPBase:     506.88000000081956,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    341.08799999952316,
		ATKAdd:     5.015999999595806,
		DEFBase:    224.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     574.4640000001527,
		HPAdd:      8.447999999858439,
		SPD:        90,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"1107101": {
		Ascension: 2,
	},
	"1107102": {
		Ascension: 4,
	},
	"1107103": {
		Ascension: 6,
	},
	"1107201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"1107202": {
		Stat: prop.PhysicalDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 2,
	},
	"1107203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"1107204": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"1107205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"1107206": {
		Stat: prop.PhysicalDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"1107207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"1107208": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"1107209": {
		Stat: prop.PhysicalDamagePercent,
		Amount: 0.06399999978020787,
		Level: 75,
	},
	"1107210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}