// Code generated by "charstat"; DO NOT EDIT.

package serval

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    88.80000000074506,
		ATKAdd:     4.440000000409782,
		DEFBase:    51,
		DEFAdd:     2.5500000005122274,
		HPBase:     124.80000000074506,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    124.32000000029802,
		ATKAdd:     4.440000000409782,
		DEFBase:    71.40000000037253,
		DEFAdd:     2.5500000005122274,
		HPBase:     174.72000000067055,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    159.8400000007823,
		ATKAdd:     4.440000000409782,
		DEFBase:    91.80000000074506,
		DEFAdd:     2.5500000005122274,
		HPBase:     224.64000000059605,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    195.36000000033528,
		ATKAdd:     4.440000000409782,
		DEFBase:    112.20000000018626,
		DEFAdd:     2.5500000005122274,
		HPBase:     274.56000000052154,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    230.88000000081956,
		ATKAdd:     4.440000000409782,
		DEFBase:    132.6000000005588,
		DEFAdd:     2.5500000005122274,
		HPBase:     324.48000000044703,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    266.40000000037253,
		ATKAdd:     4.440000000409782,
		DEFBase:    153,
		DEFAdd:     2.5500000005122274,
		HPBase:     374.40000000037253,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    301.9200000008568,
		ATKAdd:     4.440000000409782,
		DEFBase:    173.40000000037253,
		DEFAdd:     2.5500000005122274,
		HPBase:     424.320000000298,
		HPAdd:      6.240000000223517,
		SPD:        104,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectHitRate,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectHitRate,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectHitRate,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.CritChance,
		Amount: 0.05299999983981252,
		Level: 80,
	},
}