// Code generated by "charstat"; DO NOT EDIT.

package march7th

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    69.6000000005588,
		ATKAdd:     3.480000000447035,
		DEFBase:    78,
		DEFAdd:     3.9000000008381903,
		HPBase:     144,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   30,
		ATKBase:    97.44000000040978,
		ATKAdd:     3.480000000447035,
		DEFBase:    109.20000000018626,
		DEFAdd:     3.9000000008381903,
		HPBase:     201.6000000005588,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   40,
		ATKBase:    125.28000000026077,
		ATKAdd:     3.480000000447035,
		DEFBase:    140.40000000037253,
		DEFAdd:     3.9000000008381903,
		HPBase:     259.20000000018626,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   50,
		ATKBase:    153.12000000011176,
		ATKAdd:     3.480000000447035,
		DEFBase:    171.6000000005588,
		DEFAdd:     3.9000000008381903,
		HPBase:     316.80000000074506,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   60,
		ATKBase:    180.96000000089407,
		ATKAdd:     3.480000000447035,
		DEFBase:    202.80000000074506,
		DEFAdd:     3.9000000008381903,
		HPBase:     374.40000000037253,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   70,
		ATKBase:    208.80000000074506,
		ATKAdd:     3.480000000447035,
		DEFBase:    234,
		DEFAdd:     3.9000000008381903,
		HPBase:     432,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   80,
		ATKBase:    236.64000000059605,
		ATKAdd:     3.480000000447035,
		DEFBase:    265.20000000018626,
		DEFAdd:     3.9000000008381903,
		HPBase:     489.6000000005588,
		HPAdd:      7.2000000001862645,
		SPD:        101,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 2,
	},
	"203": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 5,
	},
	"208": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 6,
	},
	"209": {
		Stat: prop.IceDamagePercent,
		Amount: 0.06399999978020787,
		Level: 75,
	},
	"210": {
		Stat: prop.DEFPercent,
		Amount: 0.10000000009313226,
		Level: 80,
	},
}