// Code generated by "charstat"; DO NOT EDIT.

package tingyun

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    72,
		ATKAdd:     3.6,
		DEFBase:    54,
		DEFAdd:     2.7,
		HPBase:     115.2,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    100.8,
		ATKAdd:     3.6,
		DEFBase:    75.6,
		DEFAdd:     2.7,
		HPBase:     161.28,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    129.6,
		ATKAdd:     3.6,
		DEFBase:    97.2,
		DEFAdd:     2.7,
		HPBase:     207.36,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    158.4,
		ATKAdd:     3.6,
		DEFBase:    118.8,
		DEFAdd:     2.7,
		HPBase:     253.44,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    187.2,
		ATKAdd:     3.6,
		DEFBase:    140.4,
		DEFAdd:     2.7,
		HPBase:     299.52,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    216,
		ATKAdd:     3.6,
		DEFBase:    162,
		DEFAdd:     2.7,
		HPBase:     345.6,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    244.8,
		ATKAdd:     3.6,
		DEFBase:    183.6,
		DEFAdd:     2.7,
		HPBase:     391.68,
		HPAdd:      5.76,
		SPD:        112,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.ThunderDamagePercent,
		Amount: 0.032,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.ThunderDamagePercent,
		Amount: 0.048,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.1,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}