// Code generated by "charstat"; DO NOT EDIT.

package xueyi

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    81.6,
		ATKAdd:     4.08,
		DEFBase:    54,
		DEFAdd:     2.7,
		HPBase:     144,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    114.24,
		ATKAdd:     4.08,
		DEFBase:    75.6,
		DEFAdd:     2.7,
		HPBase:     201.6,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    146.88,
		ATKAdd:     4.08,
		DEFBase:    97.2,
		DEFAdd:     2.7,
		HPBase:     259.2,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    179.52,
		ATKAdd:     4.08,
		DEFBase:    118.8,
		DEFAdd:     2.7,
		HPBase:     316.8,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    212.16,
		ATKAdd:     4.08,
		DEFBase:    140.4,
		DEFAdd:     2.7,
		HPBase:     374.4,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    244.8,
		ATKAdd:     4.08,
		DEFBase:    162,
		DEFAdd:     2.7,
		HPBase:     432,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    277.44,
		ATKAdd:     4.08,
		DEFBase:    183.6,
		DEFAdd:     2.7,
		HPBase:     489.6,
		HPAdd:      7.2,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Level: 1,
	},
	"202": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 2,
	},
	"203": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Ascension: 3,
	},
	"204": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.032,
		Ascension: 3,
	},
	"205": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 4,
	},
	"206": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"207": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 5,
	},
	"208": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.048,
		Ascension: 6,
	},
	"209": {
		Stat: prop.HPPercent,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.BreakEffect,
		Amount: 0.107,
		Level: 80,
	},
}