// Code generated by "weapstat"; DO NOT EDIT.

package whatisreal

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   48,
		HPAdd:    7.2,
		ATKBase:  19.2,
		ATKAdd:   2.88,
		DEFBase:  15,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 30,
		HPBase:   105.6,
		HPAdd:    7.2,
		ATKBase:  42.24,
		ATKAdd:   2.88,
		DEFBase:  33,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 40,
		HPBase:   182.4,
		HPAdd:    7.2,
		ATKBase:  72.96,
		ATKAdd:   2.88,
		DEFBase:  57,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 50,
		HPBase:   259.2,
		HPAdd:    7.2,
		ATKBase:  103.68,
		ATKAdd:   2.88,
		DEFBase:  81,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 60,
		HPBase:   336,
		HPAdd:    7.2,
		ATKBase:  134.4,
		ATKAdd:   2.88,
		DEFBase:  105,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 70,
		HPBase:   412.8,
		HPAdd:    7.2,
		ATKBase:  165.12,
		ATKAdd:   2.88,
		DEFBase:  129,
		DEFAdd:   2.25,
	},
	{
		MaxLevel: 80,
		HPBase:   489.6,
		HPAdd:    7.2,
		ATKBase:  195.84,
		ATKAdd:   2.88,
		DEFBase:  153,
		DEFAdd:   2.25,
	},
}