// Code generated by "charstat"; DO NOT EDIT.

package guinaifen

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    79.2,
		ATKAdd:     3.96,
		DEFBase:    60,
		DEFAdd:     3,
		HPBase:     120,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    110.88,
		ATKAdd:     3.96,
		DEFBase:    84,
		DEFAdd:     3,
		HPBase:     168,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    142.56,
		ATKAdd:     3.96,
		DEFBase:    108,
		DEFAdd:     3,
		HPBase:     216,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    174.24,
		ATKAdd:     3.96,
		DEFBase:    132,
		DEFAdd:     3,
		HPBase:     264,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    205.92,
		ATKAdd:     3.96,
		DEFBase:    156,
		DEFAdd:     3,
		HPBase:     312,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    237.6,
		ATKAdd:     3.96,
		DEFBase:    180,
		DEFAdd:     3,
		HPBase:     360,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    269.28,
		ATKAdd:     3.96,
		DEFBase:    204,
		DEFAdd:     3,
		HPBase:     408,
		HPAdd:      6,
		SPD:        106,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.FireDamagePercent,
		Amount: 0.032,
		Level: 1,
	},
	"202": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Ascension: 2,
	},
	"203": {
		Stat: prop.FireDamagePercent,
		Amount: 0.032,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectHitRate,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.FireDamagePercent,
		Amount: 0.048,
		Ascension: 4,
	},
	"206": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 5,
	},
	"207": {
		Stat: prop.FireDamagePercent,
		Amount: 0.048,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectHitRate,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.BreakEffect,
		Amount: 0.107,
		Level: 75,
	},
	"210": {
		Stat: prop.FireDamagePercent,
		Amount: 0.064,
		Level: 80,
	},
}