// Code generated by "stringer -type=InsertPriority"; DO NOT EDIT.

package info

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharReviveSelf-45]
	_ = x[CharHealSelf-48]
	_ = x[CharReviveOthers-55]
	_ = x[CharHealOthers-58]
	_ = x[CharInsertAttackSelf-75]
	_ = x[CharInsertAttackOthers-115]
	_ = x[EnemyReviveSelf-145]
	_ = x[EnemyHealSelf-148]
	_ = x[EnemyReviveOthers-155]
	_ = x[EnemyHealOthers-158]
	_ = x[EnemyInsertAttackSelf-175]
	_ = x[EnemyInsertAttackOthers-215]
	_ = x[CharInsertUlt-500]
	_ = x[CharInsertAction-800]
	_ = x[EnemyInsertUlt-1000]
	_ = x[EnemyInsertAction-1300]
}

const _InsertPriority_name = "CharReviveSelfCharHealSelfCharReviveOthersCharHealOthersCharInsertAttackSelfCharInsertAttackOthersEnemyReviveSelfEnemyHealSelfEnemyReviveOthersEnemyHealOthersEnemyInsertAttackSelfEnemyInsertAttackOthersCharInsertUltCharInsertActionEnemyInsertUltEnemyInsertAction"

var _InsertPriority_map = map[InsertPriority]string{
	45:   _InsertPriority_name[0:14],
	48:   _InsertPriority_name[14:26],
	55:   _InsertPriority_name[26:42],
	58:   _InsertPriority_name[42:56],
	75:   _InsertPriority_name[56:76],
	115:  _InsertPriority_name[76:98],
	145:  _InsertPriority_name[98:113],
	148:  _InsertPriority_name[113:126],
	155:  _InsertPriority_name[126:143],
	158:  _InsertPriority_name[143:158],
	175:  _InsertPriority_name[158:179],
	215:  _InsertPriority_name[179:202],
	500:  _InsertPriority_name[202:215],
	800:  _InsertPriority_name[215:231],
	1000: _InsertPriority_name[231:245],
	1300: _InsertPriority_name[245:262],
}

func (i InsertPriority) String() string {
	if str, ok := _InsertPriority_map[i]; ok {
		return str
	}
	return "InsertPriority(" + strconv.FormatInt(int64(i), 10) + ")"
}
