// Code generated by "charstat"; DO NOT EDIT.

package hanya

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    76.8,
		ATKAdd:     3.84,
		DEFBase:    48,
		DEFAdd:     2.4,
		HPBase:     124.8,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    107.52,
		ATKAdd:     3.84,
		DEFBase:    67.2,
		DEFAdd:     2.4,
		HPBase:     174.72,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    138.24,
		ATKAdd:     3.84,
		DEFBase:    86.4,
		DEFAdd:     2.4,
		HPBase:     224.64,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    168.96,
		ATKAdd:     3.84,
		DEFBase:    105.6,
		DEFAdd:     2.4,
		HPBase:     274.56,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    199.68,
		ATKAdd:     3.84,
		DEFBase:    124.8,
		DEFAdd:     2.4,
		HPBase:     324.48,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    230.4,
		ATKAdd:     3.84,
		DEFBase:    144,
		DEFAdd:     2.4,
		HPBase:     374.4,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    261.12,
		ATKAdd:     3.84,
		DEFBase:    163.2,
		DEFAdd:     2.4,
		HPBase:     424.32,
		HPAdd:      6.24,
		SPD:        110,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.SPDFlat,
		Amount: 2,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.SPDFlat,
		Amount: 3,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.SPDFlat,
		Amount: 4,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}