// Code generated by "charstat"; DO NOT EDIT.

package huohuo

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    81.84000000078231,
		ATKAdd:     4.091999999945983,
		DEFBase:    69.3000000002794,
		DEFAdd:     3.465000000083819,
		HPBase:     184.80000000074506,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    114.57600000011735,
		ATKAdd:     4.091999999945983,
		DEFBase:    97.02000000001863,
		DEFAdd:     3.465000000083819,
		HPBase:     258.72000000067055,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    147.31200000015087,
		ATKAdd:     4.091999999945983,
		DEFBase:    124.74000000068918,
		DEFAdd:     3.465000000083819,
		HPBase:     332.64000000059605,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    180.0479999994859,
		ATKAdd:     4.091999999945983,
		DEFBase:    152.4600000004284,
		DEFAdd:     3.465000000083819,
		HPBase:     406.56000000052154,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    212.78400000045076,
		ATKAdd:     4.091999999945983,
		DEFBase:    180.18000000016764,
		DEFAdd:     3.465000000083819,
		HPBase:     480.48000000044703,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    245.5200000004843,
		ATKAdd:     4.091999999945983,
		DEFBase:    207.9000000008382,
		DEFAdd:     3.465000000083819,
		HPBase:     554.4000000003725,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    278.2559999998193,
		ATKAdd:     4.091999999945983,
		DEFBase:    235.62000000057742,
		DEFAdd:     3.465000000083819,
		HPBase:     628.320000000298,
		HPAdd:      9.240000000223517,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.SPDFlat,
		Amount: 2,
		Ascension: 3,
	},
	"205": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.SPDFlat,
		Amount: 3,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectRES,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}