// Code generated by "weapstat"; DO NOT EDIT.

package ishallbemyownsword

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   52.8,
		HPAdd:    7.92,
		ATKBase:  26.4,
		ATKAdd:   3.96,
		DEFBase:  18,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 30,
		HPBase:   116.16,
		HPAdd:    7.92,
		ATKBase:  58.08,
		ATKAdd:   3.96,
		DEFBase:  39.6,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 40,
		HPBase:   200.64,
		HPAdd:    7.92,
		ATKBase:  100.32,
		ATKAdd:   3.96,
		DEFBase:  68.4,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 50,
		HPBase:   285.12,
		HPAdd:    7.92,
		ATKBase:  142.56,
		ATKAdd:   3.96,
		DEFBase:  97.2,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 60,
		HPBase:   369.6,
		HPAdd:    7.92,
		ATKBase:  184.8,
		ATKAdd:   3.96,
		DEFBase:  126,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 70,
		HPBase:   454.08,
		HPAdd:    7.92,
		ATKBase:  227.04,
		ATKAdd:   3.96,
		DEFBase:  154.8,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 80,
		HPBase:   538.56,
		HPAdd:    7.92,
		ATKBase:  269.28,
		ATKAdd:   3.96,
		DEFBase:  183.6,
		DEFAdd:   2.7,
	},
}