// Code generated by "charstat"; DO NOT EDIT.

package blade

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    73.92000000085682,
		ATKAdd:     3.6960000002291054,
		DEFBase:    66,
		DEFAdd:     3.3000000002793968,
		HPBase:     184.80000000074506,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    103.48799999989569,
		ATKAdd:     3.6960000002291054,
		DEFBase:    92.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     258.72000000067055,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    133.05599999963306,
		ATKAdd:     3.6960000002291054,
		DEFBase:    118.80000000074506,
		DEFAdd:     3.3000000002793968,
		HPBase:     332.64000000059605,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    162.62400000030175,
		ATKAdd:     3.6960000002291054,
		DEFBase:    145.20000000018626,
		DEFAdd:     3.3000000002793968,
		HPBase:     406.56000000052154,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    192.19200000003912,
		ATKAdd:     3.6960000002291054,
		DEFBase:    171.6000000005588,
		DEFAdd:     3.3000000002793968,
		HPBase:     480.48000000044703,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    221.7600000007078,
		ATKAdd:     3.6960000002291054,
		DEFBase:    198,
		DEFAdd:     3.3000000002793968,
		HPBase:     554.4000000003725,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    251.32799999974668,
		ATKAdd:     3.6960000002291054,
		DEFBase:    224.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     628.320000000298,
		HPAdd:      9.240000000223517,
		SPD:        97,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Ascension: 2,
	},
	"203": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 5,
	},
	"207": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritChance,
		Amount: 0.05299999983981252,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}