---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: run all protos generation
    cmds:
      - task: go
      - task: ts-types
  go:
    desc: generate go code
    cmds:
      - |
        protoc \
              --experimental_allow_proto3_optional \
              --go_out=module=github.com/simimpact/srsim:. \
              --go-grpc_out=module=github.com/simimpact/srsim:. \
              pb/**/*.proto
  ts-types:
    desc: generate ts types
    cmds:
      - |
        protoc \
              --experimental_allow_proto3_optional \
              --plugin=./js/packages/ts-types/node_modules/.bin/protoc-gen-ts_proto \
              --ts_proto_opt=useOptionals=all \
              --ts_proto_opt=snakeToCamel=json \
              --ts_proto_out=./js/packages/ts-types/src/generated \
              --ts_proto_opt=esModuleInterop=true \
              --ts_proto_opt=useJsonName=true \
              --ts_proto_opt=outputIndex=true \
              pb/**/*.proto
