// Code generated by "charstat"; DO NOT EDIT.

package danhengimbibitorlunae

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    95.04000000003725,
		ATKAdd:     4.752000000560656,
		DEFBase:    49.50000000046566,
		DEFAdd:     2.4750000000931323,
		HPBase:     168.96000000089407,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    133.05599999963306,
		ATKAdd:     4.752000000560656,
		DEFBase:    69.3000000002794,
		DEFAdd:     2.4750000000931323,
		HPBase:     236.54400000022724,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    171.07199999992736,
		ATKAdd:     4.752000000560656,
		DEFBase:    89.10000000009313,
		DEFAdd:     2.4750000000931323,
		HPBase:     304.1279999995604,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    209.08799999952316,
		ATKAdd:     4.752000000560656,
		DEFBase:    108.90000000083819,
		DEFAdd:     2.4750000000931323,
		HPBase:     371.7120000005234,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    247.10399999981746,
		ATKAdd:     4.752000000560656,
		DEFBase:    128.70000000065193,
		DEFAdd:     2.4750000000931323,
		HPBase:     439.2959999998566,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    285.12000000011176,
		ATKAdd:     4.752000000560656,
		DEFBase:    148.50000000046566,
		DEFAdd:     2.4750000000931323,
		HPBase:     506.88000000081956,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    323.13599999970756,
		ATKAdd:     4.752000000560656,
		DEFBase:    168.3000000002794,
		DEFAdd:     2.4750000000931323,
		HPBase:     574.4640000001527,
		HPAdd:      8.447999999858439,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.CritChance,
		Amount: 0.026999999536201358,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritChance,
		Amount: 0.0400000000372529,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritChance,
		Amount: 0.05299999983981252,
		Level: 75,
	},
	"210": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}