// Code generated by "charstat"; DO NOT EDIT.

package gepard

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    73.92000000085682,
		ATKAdd:     3.6960000002291054,
		DEFBase:    89.10000000009313,
		DEFAdd:     4.455000000074506,
		HPBase:     190.0800000000745,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   30,
		ATKBase:    103.48799999989569,
		ATKAdd:     3.6960000002291054,
		DEFBase:    124.74000000068918,
		DEFAdd:     4.455000000074506,
		HPBase:     266.1119999999646,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   40,
		ATKBase:    133.05599999963306,
		ATKAdd:     3.6960000002291054,
		DEFBase:    160.3800000003539,
		DEFAdd:     4.455000000074506,
		HPBase:     342.1439999998547,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   50,
		ATKBase:    162.62400000030175,
		ATKAdd:     3.6960000002291054,
		DEFBase:    196.02000000001863,
		DEFAdd:     4.455000000074506,
		HPBase:     418.1759999997448,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   60,
		ATKBase:    192.19200000003912,
		ATKAdd:     3.6960000002291054,
		DEFBase:    231.66000000061467,
		DEFAdd:     4.455000000074506,
		HPBase:     494.2079999996349,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   70,
		ATKBase:    221.7600000007078,
		ATKAdd:     3.6960000002291054,
		DEFBase:    267.3000000002794,
		DEFAdd:     4.455000000074506,
		HPBase:     570.2400000002235,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
	{
		MaxLevel:   80,
		ATKBase:    251.32799999974668,
		ATKAdd:     3.6960000002291054,
		DEFBase:    302.94000000087544,
		DEFAdd:     4.455000000074506,
		HPBase:     646.2720000001136,
		HPAdd:      9.50400000018999,
		SPD:        92,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      150,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.IceDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 3,
	},
	"205": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.IceDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectRES,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.IceDamagePercent,
		Amount: 0.06399999978020787,
		Level: 80,
	},
}