// Code generated by "charstat"; DO NOT EDIT.

package arlan

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    81.6000000005588,
		ATKAdd:     4.080000000074506,
		DEFBase:    45,
		DEFAdd:     2.2500000002328306,
		HPBase:     163.20000000018626,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    114.24000000022352,
		ATKAdd:     4.080000000074506,
		DEFBase:    63,
		DEFAdd:     2.2500000002328306,
		HPBase:     228.48000000044703,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    146.88000000081956,
		ATKAdd:     4.080000000074506,
		DEFBase:    81,
		DEFAdd:     2.2500000002328306,
		HPBase:     293.7600000007078,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    179.5200000004843,
		ATKAdd:     4.080000000074506,
		DEFBase:    99,
		DEFAdd:     2.2500000002328306,
		HPBase:     359.04000000003725,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    212.160000000149,
		ATKAdd:     4.080000000074506,
		DEFBase:    117,
		DEFAdd:     2.2500000002328306,
		HPBase:     424.320000000298,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    244.80000000074506,
		ATKAdd:     4.080000000074506,
		DEFBase:    135,
		DEFAdd:     2.2500000002328306,
		HPBase:     489.6000000005588,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    277.4400000004098,
		ATKAdd:     4.080000000074506,
		DEFBase:    153,
		DEFAdd:     2.2500000002328306,
		HPBase:     554.8800000008196,
		HPAdd:      8.160000000149012,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectRES,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}