// Code generated by "charstat"; DO NOT EDIT.

package hook

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    84,
		ATKAdd:     4.2000000001862645,
		DEFBase:    48,
		DEFAdd:     2.400000000372529,
		HPBase:     182.40000000037253,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   30,
		ATKBase:    117.6000000005588,
		ATKAdd:     4.2000000001862645,
		DEFBase:    67.20000000018626,
		DEFAdd:     2.400000000372529,
		HPBase:     255.36000000033528,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   40,
		ATKBase:    151.20000000018626,
		ATKAdd:     4.2000000001862645,
		DEFBase:    86.40000000037253,
		DEFAdd:     2.400000000372529,
		HPBase:     328.320000000298,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   50,
		ATKBase:    184.80000000074506,
		ATKAdd:     4.2000000001862645,
		DEFBase:    105.6000000005588,
		DEFAdd:     2.400000000372529,
		HPBase:     401.28000000026077,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   60,
		ATKBase:    218.40000000037253,
		ATKAdd:     4.2000000001862645,
		DEFBase:    124.80000000074506,
		DEFAdd:     2.400000000372529,
		HPBase:     474.2400000002235,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   70,
		ATKBase:    252,
		ATKAdd:     4.2000000001862645,
		DEFBase:    144,
		DEFAdd:     2.400000000372529,
		HPBase:     547.2000000001863,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
	{
		MaxLevel:   80,
		ATKBase:    285.6000000005588,
		ATKAdd:     4.2000000001862645,
		DEFBase:    163.20000000018626,
		DEFAdd:     2.400000000372529,
		HPBase:     620.160000000149,
		HPAdd:      9.120000000111759,
		SPD:        94,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      125,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.CritDMG,
		Amount: 0.05299999983981252,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.CritDMG,
		Amount: 0.0800000000745058,
		Ascension: 6,
	},
	"209": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}