// Code generated by "charstat"; DO NOT EDIT.

package gallagher

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    72,
		ATKAdd:     3.6,
		DEFBase:    60,
		DEFAdd:     3,
		HPBase:     177.6,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    100.8,
		ATKAdd:     3.6,
		DEFBase:    84,
		DEFAdd:     3,
		HPBase:     248.64,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    129.6,
		ATKAdd:     3.6,
		DEFBase:    108,
		DEFAdd:     3,
		HPBase:     319.68,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    158.4,
		ATKAdd:     3.6,
		DEFBase:    132,
		DEFAdd:     3,
		HPBase:     390.72,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    187.2,
		ATKAdd:     3.6,
		DEFBase:    156,
		DEFAdd:     3,
		HPBase:     461.76,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    216,
		ATKAdd:     3.6,
		DEFBase:    180,
		DEFAdd:     3,
		HPBase:     532.8,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    244.8,
		ATKAdd:     3.6,
		DEFBase:    204,
		DEFAdd:     3,
		HPBase:     603.84,
		HPAdd:      8.88,
		SPD:        98,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Ascension: 2,
	},
	"203": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 5,
	},
	"207": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectRES,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.08,
		Level: 80,
	},
}