// Code generated by "weapstat"; DO NOT EDIT.

package poisedtobloom

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   43.20,
		HPAdd:    6.48,
		ATKBase:  19.20,
		ATKAdd:   2.88,
		DEFBase:  18,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 30,
		HPBase:   95.04,
		HPAdd:    6.48,
		ATKBase:  42.24,
		ATKAdd:   2.88,
		DEFBase:  39.60,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 40,
		HPBase:   164.16,
		HPAdd:    6.48,
		ATKBase:  72.96,
		ATKAdd:   2.88,
		DEFBase:  68.40,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 50,
		HPBase:   233.28,
		HPAdd:    6.48,
		ATKBase:  103.68,
		ATKAdd:   2.88,
		DEFBase:  97.20,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 60,
		HPBase:   302.40,
		HPAdd:    6.48,
		ATKBase:  134.40,
		ATKAdd:   2.88,
		DEFBase:  126,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 70,
		HPBase:   371.52,
		HPAdd:    6.48,
		ATKBase:  165.12,
		ATKAdd:   2.88,
		DEFBase:  154.80,
		DEFAdd:   2.70,
	},
	{
		MaxLevel: 80,
		HPBase:   440.64,
		HPAdd:    6.48,
		ATKBase:  195.84,
		ATKAdd:   2.88,
		DEFBase:  183.60,
		DEFAdd:   2.70,
	},
}