// Code generated by "charstat"; DO NOT EDIT.

package ruanmei

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    89.76,
		ATKAdd:     4.488,
		DEFBase:    66,
		DEFAdd:     3.3,
		HPBase:     147.84,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    125.664,
		ATKAdd:     4.488,
		DEFBase:    92.4,
		DEFAdd:     3.3,
		HPBase:     206.976,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    161.568,
		ATKAdd:     4.488,
		DEFBase:    118.8,
		DEFAdd:     3.3,
		HPBase:     266.112,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    197.472,
		ATKAdd:     4.488,
		DEFBase:    145.2,
		DEFAdd:     3.3,
		HPBase:     325.248,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    233.376,
		ATKAdd:     4.488,
		DEFBase:    171.6,
		DEFAdd:     3.3,
		HPBase:     384.384,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    269.28,
		ATKAdd:     4.488,
		DEFBase:    198,
		DEFAdd:     3.3,
		HPBase:     443.52,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    305.184,
		ATKAdd:     4.488,
		DEFBase:    224.4,
		DEFAdd:     3.3,
		HPBase:     502.656,
		HPAdd:      7.392,
		SPD:        104,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 2,
	},
	"203": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Ascension: 3,
	},
	"204": {
		Stat: prop.SPDFlat,
		Amount: 2,
		Ascension: 3,
	},
	"205": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 5,
	},
	"207": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 5,
	},
	"208": {
		Stat: prop.SPDFlat,
		Amount: 3,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.1,
		Level: 75,
	},
	"210": {
		Stat: prop.BreakEffect,
		Amount: 0.107,
		Level: 80,
	},
}