// Code generated by "charstat"; DO NOT EDIT.

package seele

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    87.12000000011176,
		ATKAdd:     4.355999999912456,
		DEFBase:    49.50000000046566,
		DEFAdd:     2.4750000000931323,
		HPBase:     126.72000000067055,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   30,
		ATKBase:    121.96800000034273,
		ATKAdd:     4.355999999912456,
		DEFBase:    69.3000000002794,
		DEFAdd:     2.4750000000931323,
		HPBase:     177.4079999998212,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   40,
		ATKBase:    156.81600000034086,
		ATKAdd:     4.355999999912456,
		DEFBase:    89.10000000009313,
		DEFAdd:     2.4750000000931323,
		HPBase:     228.0959999996703,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   50,
		ATKBase:    191.664000000339,
		ATKAdd:     4.355999999912456,
		DEFBase:    108.90000000083819,
		DEFAdd:     2.4750000000931323,
		HPBase:     278.78400000045076,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   60,
		ATKBase:    226.51200000033714,
		ATKAdd:     4.355999999912456,
		DEFBase:    128.70000000065193,
		DEFAdd:     2.4750000000931323,
		HPBase:     329.4720000002999,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   70,
		ATKBase:    261.3600000003353,
		ATKAdd:     4.355999999912456,
		DEFBase:    148.50000000046566,
		DEFAdd:     2.4750000000931323,
		HPBase:     380.160000000149,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
	{
		MaxLevel:   80,
		ATKBase:    296.2079999996349,
		ATKAdd:     4.355999999912456,
		DEFBase:    168.3000000002794,
		DEFAdd:     2.4750000000931323,
		HPBase:     430.84800000023097,
		HPAdd:      6.335999999893829,
		SPD:        115,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      75,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.CritDMG,
		Amount: 0.05299999983981252,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.CritDMG,
		Amount: 0.0800000000745058,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 6,
	},
	"209": {
		Stat: prop.CritDMG,
		Amount: 0.10699999961070716,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}