// Code generated by "weapstat"; DO NOT EDIT.

package shadowedbynight

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   38.4,
		HPAdd:    5.76,
		ATKBase:  21.6,
		ATKAdd:   3.24,
		DEFBase:  18,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 30,
		HPBase:   84.48,
		HPAdd:    5.76,
		ATKBase:  47.52,
		ATKAdd:   3.24,
		DEFBase:  39.6,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 40,
		HPBase:   145.92,
		HPAdd:    5.76,
		ATKBase:  82.08,
		ATKAdd:   3.24,
		DEFBase:  68.4,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 50,
		HPBase:   207.36,
		HPAdd:    5.76,
		ATKBase:  116.64,
		ATKAdd:   3.24,
		DEFBase:  97.2,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 60,
		HPBase:   268.8,
		HPAdd:    5.76,
		ATKBase:  151.2,
		ATKAdd:   3.24,
		DEFBase:  126,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 70,
		HPBase:   330.24,
		HPAdd:    5.76,
		ATKBase:  185.76,
		ATKAdd:   3.24,
		DEFBase:  154.8,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 80,
		HPBase:   391.68,
		HPAdd:    5.76,
		ATKBase:  220.32,
		ATKAdd:   3.24,
		DEFBase:  183.6,
		DEFAdd:   2.7,
	},
}