// Code generated by "charstat"; DO NOT EDIT.

package kafka

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    92.40000000037253,
		ATKAdd:     4.62000000057742,
		DEFBase:    66,
		DEFAdd:     3.3000000002793968,
		HPBase:     147.8400000007823,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    129.36000000033528,
		ATKAdd:     4.62000000057742,
		DEFBase:    92.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     206.97600000048988,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    166.32000000029802,
		ATKAdd:     4.62000000057742,
		DEFBase:    118.80000000074506,
		DEFAdd:     3.3000000002793968,
		HPBase:     266.1119999999646,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    203.28000000026077,
		ATKAdd:     4.62000000057742,
		DEFBase:    145.20000000018626,
		DEFAdd:     3.3000000002793968,
		HPBase:     325.2479999996722,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    240.24000000022352,
		ATKAdd:     4.62000000057742,
		DEFBase:    171.6000000005588,
		DEFAdd:     3.3000000002793968,
		HPBase:     384.38400000007823,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    277.20000000018626,
		ATKAdd:     4.62000000057742,
		DEFBase:    198,
		DEFAdd:     3.3000000002793968,
		HPBase:     443.5200000004843,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    314.160000000149,
		ATKAdd:     4.62000000057742,
		DEFBase:    224.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     502.65600000019185,
		HPAdd:      7.39200000022538,
		SPD:        100,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.BreakEffect,
		Amount: 0.05299999983981252,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.BreakEffect,
		Amount: 0.0800000000745058,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.BreakEffect,
		Amount: 0.10699999961070716,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}