// Code generated by "charstat"; DO NOT EDIT.

package silverwolf

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    87.12000000011176,
		ATKAdd:     4.355999999912456,
		DEFBase:    62.700000000651926,
		DEFAdd:     3.1349999997764826,
		HPBase:     142.56000000052154,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    121.96800000034273,
		ATKAdd:     4.355999999912456,
		DEFBase:    87.78000000072643,
		DEFAdd:     3.1349999997764826,
		HPBase:     199.5840000002645,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    156.81600000034086,
		ATKAdd:     4.355999999912456,
		DEFBase:    112.86000000080094,
		DEFAdd:     3.1349999997764826,
		HPBase:     256.60800000000745,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    191.664000000339,
		ATKAdd:     4.355999999912456,
		DEFBase:    137.94000000087544,
		DEFAdd:     3.1349999997764826,
		HPBase:     313.6320000004489,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    226.51200000033714,
		ATKAdd:     4.355999999912456,
		DEFBase:    163.02000000001863,
		DEFAdd:     3.1349999997764826,
		HPBase:     370.65600000019185,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    261.3600000003353,
		ATKAdd:     4.355999999912456,
		DEFBase:    188.10000000009313,
		DEFAdd:     3.1349999997764826,
		HPBase:     427.6800000006333,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    296.2079999996349,
		ATKAdd:     4.355999999912456,
		DEFBase:    213.18000000016764,
		DEFAdd:     3.1349999997764826,
		HPBase:     484.70400000037625,
		HPAdd:      7.127999999560416,
		SPD:        107,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectHitRate,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.031999999890103936,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectHitRate,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.QuantumDamagePercent,
		Amount: 0.04799999948590994,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectHitRate,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}