// Code generated by "weapstat"; DO NOT EDIT.

package destinysthreadsforewoven

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   43.2,
		HPAdd:    6.48,
		ATKBase:  16.8,
		ATKAdd:   2.52,
		DEFBase:  21,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 30,
		HPBase:   95.04,
		HPAdd:    6.48,
		ATKBase:  36.96,
		ATKAdd:   2.52,
		DEFBase:  46.2,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 40,
		HPBase:   164.16,
		HPAdd:    6.48,
		ATKBase:  63.84,
		ATKAdd:   2.52,
		DEFBase:  79.8,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 50,
		HPBase:   233.28,
		HPAdd:    6.48,
		ATKBase:  90.72,
		ATKAdd:   2.52,
		DEFBase:  113.4,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 60,
		HPBase:   302.4,
		HPAdd:    6.48,
		ATKBase:  117.6,
		ATKAdd:   2.52,
		DEFBase:  147,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 70,
		HPBase:   371.52,
		HPAdd:    6.48,
		ATKBase:  144.48,
		ATKAdd:   2.52,
		DEFBase:  180.6,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 80,
		HPBase:   440.64,
		HPAdd:    6.48,
		ATKBase:  171.36,
		ATKAdd:   2.52,
		DEFBase:  214.2,
		DEFAdd:   3.15,
	},
}