// Code generated by "weapstat"; DO NOT EDIT.

package heyoverhere

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   43.2,
		HPAdd:    6.48,
		ATKBase:  19.2,
		ATKAdd:   2.88,
		DEFBase:  18,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 30,
		HPBase:   95.04,
		HPAdd:    6.48,
		ATKBase:  42.24,
		ATKAdd:   2.88,
		DEFBase:  39.6,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 40,
		HPBase:   164.16,
		HPAdd:    6.48,
		ATKBase:  72.96,
		ATKAdd:   2.88,
		DEFBase:  68.4,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 50,
		HPBase:   233.28,
		HPAdd:    6.48,
		ATKBase:  103.68,
		ATKAdd:   2.88,
		DEFBase:  97.2,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 60,
		HPBase:   302.4,
		HPAdd:    6.48,
		ATKBase:  134.4,
		ATKAdd:   2.88,
		DEFBase:  126,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 70,
		HPBase:   371.52,
		HPAdd:    6.48,
		ATKBase:  165.12,
		ATKAdd:   2.88,
		DEFBase:  154.8,
		DEFAdd:   2.7,
	},
	{
		MaxLevel: 80,
		HPBase:   440.64,
		HPAdd:    6.48,
		ATKBase:  195.84,
		ATKAdd:   2.88,
		DEFBase:  183.6,
		DEFAdd:   2.7,
	},
}