name: "Setup go and Run Tests"
description: "runs setup-go and runs all unit tests in the repo"
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "^1.23"
    - name: Run Tests
      working-directory: ./
      shell: bash
      run: "go test ./pkg/... ./tests/..."
# TODO: go test ./internal/... ./pkg/... ./backend/...
