// Code generated by "charstat"; DO NOT EDIT.

package luka

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    79.2,
		ATKAdd:     3.96,
		DEFBase:    66,
		DEFAdd:     3.3,
		HPBase:     124.8,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    110.88,
		ATKAdd:     3.96,
		DEFBase:    92.4,
		DEFAdd:     3.3,
		HPBase:     174.72,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    142.56,
		ATKAdd:     3.96,
		DEFBase:    118.8,
		DEFAdd:     3.3,
		HPBase:     224.64,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    174.24,
		ATKAdd:     3.96,
		DEFBase:    145.2,
		DEFAdd:     3.3,
		HPBase:     274.56,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    205.92,
		ATKAdd:     3.96,
		DEFBase:    171.6,
		DEFAdd:     3.3,
		HPBase:     324.48,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    237.6,
		ATKAdd:     3.96,
		DEFBase:    198,
		DEFAdd:     3.3,
		HPBase:     374.4,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    269.28,
		ATKAdd:     3.96,
		DEFBase:    224.4,
		DEFAdd:     3.3,
		HPBase:     424.32,
		HPAdd:      6.24,
		SPD:        103,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectHitRate,
		Amount: 0.04,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.04,
		Ascension: 3,
	},
	"204": {
		Stat: prop.DEFPercent,
		Amount: 0.05,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectHitRate,
		Amount: 0.06,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.06,
		Ascension: 5,
	},
	"208": {
		Stat: prop.DEFPercent,
		Amount: 0.075,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectHitRate,
		Amount: 0.08,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.08,
		Level: 80,
	},
}