// Code generated by "charstat"; DO NOT EDIT.

package bailu

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    76.56000000052154,
		ATKAdd:     3.8280000002123415,
		DEFBase:    66,
		DEFAdd:     3.3000000002793968,
		HPBase:     179.5200000004843,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    107.18399999989197,
		ATKAdd:     3.8280000002123415,
		DEFBase:    92.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     251.32799999974668,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    137.80800000019372,
		ATKAdd:     3.8280000002123415,
		DEFBase:    118.80000000074506,
		DEFAdd:     3.3000000002793968,
		HPBase:     323.13599999970756,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    168.43200000026263,
		ATKAdd:     3.8280000002123415,
		DEFBase:    145.20000000018626,
		DEFAdd:     3.3000000002793968,
		HPBase:     394.9440000005998,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    199.05599999963306,
		ATKAdd:     3.8280000002123415,
		DEFBase:    171.6000000005588,
		DEFAdd:     3.3000000002793968,
		HPBase:     466.75200000056066,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    229.6800000006333,
		ATKAdd:     3.8280000002123415,
		DEFBase:    198,
		DEFAdd:     3.3000000002793968,
		HPBase:     538.5600000005215,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    260.3040000000037,
		ATKAdd:     3.8280000002123415,
		DEFBase:    224.40000000037253,
		DEFAdd:     3.3000000002793968,
		HPBase:     610.3679999997839,
		HPAdd:      8.976000000489876,
		SPD:        98,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.DEFPercent,
		Amount: 0.05000000004656613,
		Ascension: 2,
	},
	"203": {
		Stat: prop.HPPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.DEFPercent,
		Amount: 0.07499999972060323,
		Ascension: 5,
	},
	"207": {
		Stat: prop.HPPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.DEFPercent,
		Amount: 0.10000000009313226,
		Level: 75,
	},
	"210": {
		Stat: prop.HPPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}