// Code generated by "weapstat"; DO NOT EDIT.

package whereaboutsshoulddreamsrest

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   52.8,
		HPAdd:    7.92,
		ATKBase:  21.6,
		ATKAdd:   3.24,
		DEFBase:  24,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 30,
		HPBase:   116.16,
		HPAdd:    7.92,
		ATKBase:  47.52,
		ATKAdd:   3.24,
		DEFBase:  52.8,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 40,
		HPBase:   200.64,
		HPAdd:    7.92,
		ATKBase:  82.08,
		ATKAdd:   3.24,
		DEFBase:  91.2,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 50,
		HPBase:   285.12,
		HPAdd:    7.92,
		ATKBase:  116.64,
		ATKAdd:   3.24,
		DEFBase:  129.6,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 60,
		HPBase:   369.6,
		HPAdd:    7.92,
		ATKBase:  151.2,
		ATKAdd:   3.24,
		DEFBase:  168,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 70,
		HPBase:   454.08,
		HPAdd:    7.92,
		ATKBase:  185.76,
		ATKAdd:   3.24,
		DEFBase:  206.4,
		DEFAdd:   3.6,
	},
	{
		MaxLevel: 80,
		HPBase:   538.56,
		HPAdd:    7.92,
		ATKBase:  220.32,
		ATKAdd:   3.24,
		DEFBase:  244.8,
		DEFAdd:   3.6,
	},
}