// Code generated by "charstat"; DO NOT EDIT.

package sampo

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    84,
		ATKAdd:     4.2000000001862645,
		DEFBase:    54,
		DEFAdd:     2.700000000651926,
		HPBase:     139.20000000018626,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    117.6000000005588,
		ATKAdd:     4.2000000001862645,
		DEFBase:    75.6000000005588,
		DEFAdd:     2.700000000651926,
		HPBase:     194.88000000081956,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    151.20000000018626,
		ATKAdd:     4.2000000001862645,
		DEFBase:    97.20000000018626,
		DEFAdd:     2.700000000651926,
		HPBase:     250.56000000052154,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    184.80000000074506,
		ATKAdd:     4.2000000001862645,
		DEFBase:    118.80000000074506,
		DEFAdd:     2.700000000651926,
		HPBase:     306.2400000002235,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    218.40000000037253,
		ATKAdd:     4.2000000001862645,
		DEFBase:    140.40000000037253,
		DEFAdd:     2.700000000651926,
		HPBase:     361.9200000008568,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    252,
		ATKAdd:     4.2000000001862645,
		DEFBase:    162,
		DEFAdd:     2.700000000651926,
		HPBase:     417.6000000005588,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    285.6000000005588,
		ATKAdd:     4.2000000001862645,
		DEFBase:    183.6000000005588,
		DEFAdd:     2.700000000651926,
		HPBase:     473.28000000026077,
		HPAdd:      6.96000000089407,
		SPD:        102,
		CritChance: 0.05000000004656613,
		CritDMG:    0.5000000004656613,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Level: 1,
	},
	"202": {
		Stat: prop.EffectHitRate,
		Amount: 0.0400000000372529,
		Ascension: 2,
	},
	"203": {
		Stat: prop.ATKPercent,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.0400000000372529,
		Ascension: 3,
	},
	"205": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 4,
	},
	"206": {
		Stat: prop.EffectHitRate,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"207": {
		Stat: prop.ATKPercent,
		Amount: 0.060000000055879354,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.060000000055879354,
		Ascension: 6,
	},
	"209": {
		Stat: prop.EffectHitRate,
		Amount: 0.0800000000745058,
		Level: 75,
	},
	"210": {
		Stat: prop.ATKPercent,
		Amount: 0.0800000000745058,
		Level: 80,
	},
}