// Code generated by "charstat"; DO NOT EDIT.

package trailblazerimaginary

import (
	"github.com/simimpact/srsim/pkg/engine/prop"
	"github.com/simimpact/srsim/pkg/engine/target/character"
)

var promotions = []character.PromotionData{
	{
		MaxLevel:   20,
		ATKBase:    60.72,
		ATKAdd:     3.036,
		DEFBase:    92.4,
		DEFAdd:     4.62,
		HPBase:     147.84,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   30,
		ATKBase:    85.008,
		ATKAdd:     3.036,
		DEFBase:    129.36,
		DEFAdd:     4.62,
		HPBase:     206.976,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   40,
		ATKBase:    109.296,
		ATKAdd:     3.036,
		DEFBase:    166.32,
		DEFAdd:     4.62,
		HPBase:     266.112,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   50,
		ATKBase:    133.584,
		ATKAdd:     3.036,
		DEFBase:    203.28,
		DEFAdd:     4.62,
		HPBase:     325.248,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   60,
		ATKBase:    157.872,
		ATKAdd:     3.036,
		DEFBase:    240.24,
		DEFAdd:     4.62,
		HPBase:     384.384,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   70,
		ATKBase:    182.16,
		ATKAdd:     3.036,
		DEFBase:    277.2,
		DEFAdd:     4.62,
		HPBase:     443.52,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
	{
		MaxLevel:   80,
		ATKBase:    206.448,
		ATKAdd:     3.036,
		DEFBase:    314.16,
		DEFAdd:     4.62,
		HPBase:     502.656,
		HPAdd:      7.392,
		SPD:        105,
		CritChance: 0.05,
		CritDMG:    0.5,
		Aggro:      100,
	},
}

var traces = character.TraceMap{
	"101": {
		Ascension: 2,
	},
	"102": {
		Ascension: 4,
	},
	"103": {
		Ascension: 6,
	},
	"201": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Level: 1,
	},
	"202": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.032,
		Ascension: 2,
	},
	"203": {
		Stat: prop.BreakEffect,
		Amount: 0.053,
		Ascension: 3,
	},
	"204": {
		Stat: prop.EffectRES,
		Amount: 0.04,
		Ascension: 3,
	},
	"205": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 4,
	},
	"206": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.048,
		Ascension: 5,
	},
	"207": {
		Stat: prop.BreakEffect,
		Amount: 0.08,
		Ascension: 5,
	},
	"208": {
		Stat: prop.EffectRES,
		Amount: 0.06,
		Ascension: 6,
	},
	"209": {
		Stat: prop.ImaginaryDamagePercent,
		Amount: 0.064,
		Level: 75,
	},
	"210": {
		Stat: prop.BreakEffect,
		Amount: 0.107,
		Level: 80,
	},
}