// Code generated by "weapstat"; DO NOT EDIT.

package reforgedremembrance

import "github.com/simimpact/srsim/pkg/engine/equip/lightcone"

var promotions = []lightcone.PromotionData{
	{
		MaxLevel: 20,
		HPBase:   48,
		HPAdd:    7.2,
		ATKBase:  26.4,
		ATKAdd:   3.96,
		DEFBase:  21,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 30,
		HPBase:   105.6,
		HPAdd:    7.2,
		ATKBase:  58.08,
		ATKAdd:   3.96,
		DEFBase:  46.2,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 40,
		HPBase:   182.4,
		HPAdd:    7.2,
		ATKBase:  100.32,
		ATKAdd:   3.96,
		DEFBase:  79.8,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 50,
		HPBase:   259.2,
		HPAdd:    7.2,
		ATKBase:  142.56,
		ATKAdd:   3.96,
		DEFBase:  113.4,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 60,
		HPBase:   336,
		HPAdd:    7.2,
		ATKBase:  184.8,
		ATKAdd:   3.96,
		DEFBase:  147,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 70,
		HPBase:   412.8,
		HPAdd:    7.2,
		ATKBase:  227.04,
		ATKAdd:   3.96,
		DEFBase:  180.6,
		DEFAdd:   3.15,
	},
	{
		MaxLevel: 80,
		HPBase:   489.6,
		HPAdd:    7.2,
		ATKBase:  269.28,
		ATKAdd:   3.96,
		DEFBase:  214.2,
		DEFAdd:   3.15,
	},
}
